---
- hosts: localhost
  gather_facts: no

  # create global modifiers
  module_defaults:
    group/aws:
      region: "us-east-2"
  tasks:

    #create vpc
    - name: create VPC
      ec2_vpc_net:
        name: ig-VPC-lac0084
        cidr_block: 10.0.0.0/16
        tags:
          Module: 5
          Name: ig-VPC-lac0084
        state: present
      register: vpc

    # create public subnets
    - name: create public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.1.0/24
        tags:
          Name: ig-public-subnet-1
          Module: 5
        state: present
      register: ig_ps_1

    # create private subnets
    - name: create private subnets 1 & 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.2.0/24
        tags:
          Name: ig-private-subnet-1
          Module: 5
        state: present
      register: ig_pvs_1

    # create internet gateway
    - name: create IGW
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ig-igw-mod5
        state: present
      register: igw

    # create nat gateway
    - name:
      ec2_vpc_nat_gateway:
        state: present
        subnet_id: "{{ ig_ps_1.subnet.id }}"
        wait: yes
        if_exist_do_not_create: true
      register: ig_nat_1

    
    # create public route table
    - name: create public route table
      ec2_vpc_route_table:
          vpc_id: "{{ vpc.vpc.id }}"
          tags:
            Name: ig-public-route-table-m5
          subnets:
            - "{{ ig_ps_1.subnet.id }}"
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ igw.gateway_id }}"
          state: present
      register: ig_prt_1



    # create security group








    - name: debug
      debug: var=igw