---
all: 
   hosts: 
    ec2-3-128-139-228.us-east-2.compute.amazonaws.com: 
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python
    ec2-3-128-154-102.us-east-2.compute.amazonaws.com: 
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python
    ec2-3-18-218-193.us-east-2.compute.amazonaws.com:
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python
   