---
- hosts: localhost
  gather_facts: no

  module_defaults:
    group/aws:
      region: us-east-2

  tasks:
    - elb_target_group:
        name: "ig-target-group-mod5"
        protocol: http
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
        stickiness_enabled: no
        stickiness_type: source_ip
        health_check_path: /
        state: present
      register: target_group