/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery.tools.UserAdmin;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) throws Exception {
        String portString = System.getenv("JETTY_PORT");

        if (portString == null || portString.equals("")) {
            port(80);
        } else {
            port(Integer.parseInt(portString));
        }
        new User().addRoutes();

        // MainMenu.menu();
        // S3.demo();
    }
}
